// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mt/sdk.go
//
// Generated by command:
//	mockgen -package=mt -source=sdk.go -destination=mocks.go

package mt

import (
	"context"
	"reflect"
	"testing"

	gomock "go.uber.org/mock/gomock"
)

// MockISDK is a mock of ISDK interface.
type MockISDK[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockISDKMockRecorder[T]
	isgomock struct{}
}

// MockISDKMockRecorder is the mock recorder for MockISDK.
type MockISDKMockRecorder[T any] struct {
	mock *MockISDK[T]
}

// NewMockISDK creates a new mock instance.
func NewMockISDK[T any](ctrl *gomock.Controller) *MockISDK[T] {
	mock := &MockISDK[T]{ctrl: ctrl}
	mock.recorder = &MockISDKMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows expected use.
func (m *MockISDK[T]) EXPECT() *MockISDKMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockISDK[T]) Get(ctx context.Context) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(T)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockISDKMockRecorder[T]) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockISDK[T])(nil).Get), ctx)
}

// Map mocks base method.
func (m *MockISDK[T]) Map(f func(string, T)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Map", f)
}

// Map indicates an expected call of Map.
func (mr *MockISDKMockRecorder[T]) Map(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockISDK[T])(nil).Map), f)
}

// MockISDKE is a mock of ISDKE interface.
type MockISDKE[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockISDKEMockRecorder[T]
	isgomock struct{}
}

// MockISDKEMockRecorder is the mock recorder for MockISDKE.
type MockISDKEMockRecorder[T any] struct {
	mock *MockISDKE[T]
}

// NewMockISDKE creates a new mock instance.
func NewMockISDKE[T any](ctrl *gomock.Controller) *MockISDKE[T] {
	mock := &MockISDKE[T]{ctrl: ctrl}
	mock.recorder = &MockISDKEMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows expected use.
func (m *MockISDKE[T]) EXPECT() *MockISDKEMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockISDKE[T]) Get(ctx context.Context) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockISDKEMockRecorder[T]) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockISDKE[T])(nil).Get), ctx)
}

// IsCentralized mocks base method.
func (m *MockISDKE[T]) IsCentralized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCentralized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCentralized indicates an expected call of IsCentralized.
func (mr *MockISDKEMockRecorder[T]) IsCentralized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCentralized", reflect.TypeOf((*MockISDKE[T])(nil).IsCentralized))
}

// NewISDKMock creates a mock for ISDK[T] (test helper).
func NewISDKMock[T any](t testing.TB) (*gomock.Controller, *MockISDK[T]) {
	ctrl := gomock.NewController(t)
	return ctrl, NewMockISDK[T](ctrl)
}

// NewISDKEMock creates a mock for ISDKE[T] (test helper).
func NewISDKEMock[T any](t testing.TB) (*gomock.Controller, *MockISDKE[T]) {
	ctrl := gomock.NewController(t)
	return ctrl, NewMockISDKE[T](ctrl)
}
